### ISSUE TITLE
Garage Parameters 

### ISSUE THREAD

**Issue by Jbb08** [rasod/homebridge-dummy-garage#1]
First up I love this dummy garage for CarPlay and many thanks for it!!
I just wanted to know if it was possible to modify the Garage specific fields like Model, Manufacturer, Serial, firmware fields? Just so I can make it look like a real door ;-)
These might be able to be manipulated in the config of this plugin?
![F72B7C9A-6823-4871-9521-E7D5A2E918E4](https://user-images.githubusercontent.com/48804661/72481353-26c0bc00-37f2-11ea-8e9e-de2649522736.png)

**Comment by rasod** [comment]
I just published an update that will fill in this info.
