### ISSUE TITLE
Homebridge 2.0

### ISSUE THREAD

**Issue by spaceg00se-r** [rasod/homebridge-dummy-garage#15]
Hi 

Will your plugin be compatible with Homebridge 2.0 (https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0)? Do you plan to make the changes to the plugin and/or the package.json file as described in the link above?

**Comment by rasod** [comment]
I did some quick tests with v2.0.0-beta.23 - seems to all work.
